### ISSUE TITLE
Broken in incognito Mode in Chrome

### ISSUE THREAD

**Issue by chstdu** [dessant/web-archives#59]
**System**

* OS name: ChromeOS
* Browser name: Chrome
* Browser version: 105.0.5195.134
* Extension version: 3.1.0

**Bug description**

Clicking on a search engine / archive in context menu or in browser overlay does nothing when in incognito mode.

**Logs**

```
script.js:1 Uncaught (in promise) Error: No current window
    at script.js:1:9048
(anonymous) @ script.js:1
await in (anonymous) (async)
(anonymous) @ script.js:1
```

**Comment by chstdu** [comment]
It is working fine in incognito mode in Chrome on Windows 10. I will try again next weekend when I am using ChromeOS again.

**Comment by dessant** [comment]
Does it also fail to work if you're not in incognito on ChromeOS?

**Comment by chstdu** [comment]
Thank you for your response! It seems to work fine if I am not in incognito mode on ChromeOS. Anything else that I could test or help?

**Comment by dessant** [comment]
If you have access to a second Chromebook, please also check there to confirm that this is not just an issue with your device. I'd like to debug the issue myself, but there does not seem to be an easy way to run ChromeOS Flex in a virtual machine, though people have posted some workarounds that I'll need to test.

**Comment by chstdu** [comment]
Unfortunately, I don't have access to a second Chromebook but I now installed the extension also on a second user account on the same Chromebook. The behavior in the incognito mode is the same:

- Clicking on an entry in the right-click menu does nothing.
- Clicking on the extension icon next to the address bar opens an overlay but does not show any archives.

**Comment by dessant** [comment]
I was finally able to install ChromeOS Flex 141 in a virtual machine, and Web Archives works as expected in Incognito. Archive sources are correctly displayed in the toolbar popup, and searches initiated from the context menu also work. It's possible that the bug you were seeing in ChromeOS was fixed by Google in the last few years, please let me know if the issue is still present with the latest version of ChromeOS.

<img width="3196" height="1994" alt="Image" src="https://github.com/user-attachments/assets/83ee3b38-afd8-49db-bdf3-af3b19695184" />

**Comment by dessant** [comment]
Let's also check if there is a logged error in that tiny popup. Please right-click on the popup and select "Inspect", then go to the Console tab in the Chrome popup that is opened. If there was any error while the popup was initialized, it should appear there.

**Comment by chstdu** [comment]
Thanks a lot for the quick reply. The version is indeed 7.1.0 but for the other questions I have to check back next weekend again when I am back at the Chromebook's owner's home.

**Comment by chstdu** [comment]
Thanks a lot for your patience! When trying the right-click context menu variant in incognito, and then choosing a search engine, nothing happens and the following error is logged in the "Service Worker (Anonym)" Console:

> script.js:1 Uncaught (in promise) Error: No current window
    at script.js:1:8998
(anonymous) @ script.js:1

The script.js link leads to the following location in the code:

> const r = (t, n) => (...a) => {
                            e.runtime.lastError ? t.reject(new Error(e.runtime.lastError.message)) : n.singleCallbackArg || a.length <= 1 && !1 !== n.singleCallbackArg ? t.resolve(a[0]) : t.resolve(a)
                        }

When I right-click inside the tiny pop-up from the browser toolbar, no error is shown in the Console and here is the screenshot of the computed sizes of the element:

<img width="1360" height="673" alt="Image" src="https://github.com/user-attachments/assets/522ce464-9168-49c3-8a1e-c43a5c3bc157" />

When I left-click inside the tiny pop-up from the browser toolbar the following error is shown in the Console:

> script.js:2 TypeError: Cannot read properties of undefined (reading 'index')
    at g (script.js:1:15844)
    at async Proxy.showContribute (script.js:1:4161)
(anonymous) @ script.js:2
c @ script.js:2
(anonymous) @ script.js:2
Promise.catch
i @ script.js:2
i @ script.js:2
n @ script.js:2

When manually changing the size of the tiny pop-up, I can see the extension but clicking on a search engine does not work either and I cannot post an error because the Inspect-window closes together with the extension pop-up right away:

<img width="1057" height="583" alt="Image" src="https://github.com/user-attachments/assets/9d895c01-6353-4c1e-a29e-ce955496c8ae" />
